### ISSUE TITLE
No git available in images?

### ISSUE THREAD

**Issue by davidwindell** [drone/images#43]
It looks like git has been removed from the ubuntu base image which causes drone builds to fail with:

`/usr/local/bin/drone: line 75: git: command not found`

**Comment by bradrydzewski** [comment]
the ubuntu image is the ubuntu-server distro from the ubuntu downloads page. It is stock Ubuntu and doesn't have Git installed:
https://registry.hub.docker.com/u/bradrydzewski/ubuntu/tags/manage/

We then have a base image that installs Git, Hg, etc:
https://registry.hub.docker.com/u/bradrydzewski/base/tags/manage/
https://github.com/drone/images/blob/master/builder/base/scripts/all.sh

All other images build on top of the base image. We haven't changed the base image since December 2014 so this would definitely be unexpected for git to not be present.

**Comment by davidwindell** [comment]
Gotcha, changing image `ubuntu` to `bradrydzewski/base` solves the problem for me. I only require a very basic image to build a Dockerfile and deploy which base should do the job.

Thanks!
